version: '3'

services:
  mongodb:
    image: 'mongo'
    ports:
      - 27017:27017
    container_name: mongodb
    volumes:
      - ./docker-data/mongo:/data/db
    networks:
      - e-commerce-project
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongodb
    networks:
      - e-commerce-project
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - '8091:8091'
    restart: always
    volumes:
      - ./docker-data/mongo:/data/db

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: order_db
      MYSQL_PASSWORD: 1234
    ports:
      - 3307:3306
    volumes:
      - ./docker-data/mysql:/var/lib/mysql
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - e-commerce-project


networks:
  e-commerce-project:
    driver: bridge